
name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      spark:
        image: apache/spark:latest
        ports:
          - 4040:4040
        options: --memory=4g --cpus=2

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run PySpark tests
      run: |
        pytest tests/test_etl.py

  deploy:
    runs-on: ubuntu-latest
    needs: test  # This ensures the deployment only runs if the test job succeeds

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy application
      run: |
        # Add your deployment commands here
        echo "Deploying application..."
